baseurl: ""
permalink: pretty
markdown: rdiscount
paginate: 10
paginate_path: "page/:num"
timezone: Europe/Paris
excerpt_separator: "Lireplus"
defaults:
 -
  scope:
    path: posts
  values:
    layout: post
 -
  scope:
    path: posts/enregistrements
  values:
    layout: audio
sass:
  style: compressed
exclude:
  - images/*.xcf
prose:
  rooturl: 'posts'
  ignore: 'enregistrements'
  siteurl: 'http://scholavesperis.github.io/'
  relativeLinks: 'http://scholavesperis.github.io/links.jsonp'
  media: 'images'
  metadata:
    posts:
      - name: "title"
        field:
          element: "text"
          label: "Titre"
          value: ""
      - name: "desc"
        field:
          element: "text"
          label: "Description"
          value: ""
    posts/enregistrements:
      - name: "title"
        field:
          element: "text"
          label: "Titre de l'article"
          value: ""
      - name: "name"
        field:
          element: "text"
          label: "Titre"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Auteur"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Lien"
          value: ""