baseurl: /
permalink: pretty
markdown: rdiscount
paginate: 10
paginate_path: "page/:num"
timezone: Europe/Paris
defaults:
 -
  scope:
    path: posts
  values:
    layout: post
sass:
  style: compressed
prose:
  rooturl: 'posts'
  siteurl: 'http://scholavesperis.github.io/'
  relativeLinks: 'http://scholavesperis.github.io/links.jsonp'
  media: 'media'
  metadata:
    posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "desc"
        field:
          element: "text"
          label: "Description"
          value: ""
    posts/enregistrements:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "auteur"
        field:
          element: "text"
          label: "Auteur"
          value: ""
      - name: "file_link"
        field:
          element: "text"
          label: "Lien du fichier"
          value: ""