baseurl: /
permalink: pretty
markdown: rdiscount
paginate: 10
paginate_path: "page/:num"
timezone: Europe/Paris
defaults:
 -
  scope:
    path: posts
  values:
    layout: post
prose:
  rooturl: 'posts'
  siteurl: 'http://scholavesperis.github.io/'
  relativeLinks: 'http://scholavesperis.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""